#!/usr/bin/env python3
"""
Generate SQL to load dry-run Pokumon preview rows into staging_pokumon_cards.

Usage:
  python scripts/generate_pokumon_staging_sql.py
  python scripts/generate_pokumon_staging_sql.py --input tmp/pokumon_pilot_preview.json --output tmp/pokumon_staging_load.sql
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build SQL loader for staging_pokumon_cards.")
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("tmp/pokumon_pilot_preview.json"),
        help="Path to dry-run preview JSON.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("tmp/pokumon_staging_load.sql"),
        help="Output SQL path.",
    )
    return parser.parse_args()


def sql_text(value: Any) -> str:
    if value is None:
        return "NULL"
    s = str(value)
    return "'" + s.replace("'", "''") + "'"


def sql_bool(value: Any) -> str:
    return "true" if bool(value) else "false"


def sql_json(value: Any) -> str:
    payload = json.dumps(value if value is not None else [], ensure_ascii=False)
    return sql_text(payload) + "::jsonb"


def build_values_row(row: dict[str, Any]) -> str:
    cols = [
        sql_text(row.get("record_id")),
        "NULL" if row.get("wp_post_id") is None else str(int(row.get("wp_post_id"))),
        sql_text(row.get("name")),
        sql_text(row.get("title_raw")),
        sql_text(row.get("detail_raw")),
        sql_text(row.get("number_guess")),
        sql_text(row.get("set_name_guess")),
        sql_json(row.get("language", [])),
        sql_json(row.get("artist", [])),
        sql_json(row.get("holofoil", [])),
        sql_json(row.get("release_event", [])),
        sql_json(row.get("release_year", [])),
        sql_json(row.get("release_month", [])),
        sql_json(row.get("release_type", [])),
        sql_json(row.get("card_type", [])),
        sql_json(row.get("additional_attributes", [])),
        sql_json(row.get("cardname", [])),
        sql_json(row.get("prefix", [])),
        sql_json(row.get("suffix", [])),
        sql_json(row.get("media_meta", {})),
        sql_text(row.get("image_url")),
        sql_text(row.get("source_link")),
        sql_text(row.get("slug")),
        sql_text(row.get("origin", "manual")),
        sql_text(row.get("origin_detail", "pokumon")),
        sql_bool(row.get("is_promo", True)),
        sql_text(row.get("raw_date_gmt")),
        sql_text(row.get("raw_modified_gmt")),
    ]
    return "(" + ", ".join(cols) + ")"


def main() -> int:
    args = parse_args()
    payload = json.loads(args.input.read_text(encoding="utf-8"))
    rows = payload.get("rows", [])

    header = """-- Auto-generated by scripts/generate_pokumon_staging_sql.py
-- Loads dry-run rows into public.staging_pokumon_cards (upsert by record_id).
-- Run scripts/pokumon_staging_review.sql first to ensure table exists.

begin;
"""
    columns = """insert into public.staging_pokumon_cards (
  record_id,
  wp_post_id,
  name,
  title_raw,
  detail_raw,
  number_guess,
  set_name_guess,
  language,
  artist,
  holofoil,
  release_event,
  release_year,
  release_month,
  release_type,
  card_type,
  additional_attributes,
  cardname,
  prefix,
  suffix,
  media_meta,
  image_url,
  source_link,
  slug,
  origin,
  origin_detail,
  is_promo,
  raw_date_gmt,
  raw_modified_gmt
) values
"""
    value_lines = ",\n".join(build_values_row(row) for row in rows)
    conflict = """
on conflict (record_id) do update set
  wp_post_id = excluded.wp_post_id,
  name = excluded.name,
  title_raw = excluded.title_raw,
  detail_raw = excluded.detail_raw,
  number_guess = excluded.number_guess,
  set_name_guess = excluded.set_name_guess,
  language = excluded.language,
  artist = excluded.artist,
  holofoil = excluded.holofoil,
  release_event = excluded.release_event,
  release_year = excluded.release_year,
  release_month = excluded.release_month,
  release_type = excluded.release_type,
  card_type = excluded.card_type,
  additional_attributes = excluded.additional_attributes,
  cardname = excluded.cardname,
  prefix = excluded.prefix,
  suffix = excluded.suffix,
  media_meta = excluded.media_meta,
  image_url = excluded.image_url,
  source_link = excluded.source_link,
  slug = excluded.slug,
  origin = excluded.origin,
  origin_detail = excluded.origin_detail,
  is_promo = excluded.is_promo,
  raw_date_gmt = excluded.raw_date_gmt,
  raw_modified_gmt = excluded.raw_modified_gmt,
  imported_at = now();

commit;
"""
    sql = header + columns + value_lines + conflict
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(sql, encoding="utf-8")
    print(f"Wrote staging SQL: {args.output} (rows={len(rows)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
