#!/usr/bin/env python3
"""Generate the one-time SQL that names PTCG-db Japanese sets from the reviewed table.

Reads ``scripts/data/japanese_set_names.json`` (owner-approved) and writes one
transaction that:

1. upserts every published PTCG-db set (name, series, release date), which names
   the existing rows and inserts the ``ja-*`` sets; English sets are never written;
2. moves cards whose code is published under another set ID (``sv9`` → ``ja-sv9``,
   ``xy6`` → ``xy6-b``); card IDs do not change;
3. fills ``set_name`` / ``set_series`` on every PTCG-db card from its set;
4. checks the result (aborting the transaction on any mismatch) and refreshes
   ``explore_filter_options``.

ptcgdb is not in the weekly push, so production changes only through this SQL.
The push (``--include-ptcgdb``) reads the same JSON and publishes the same values.

Usage::

  python scripts/generate_ptcgdb_set_names_sql.py OUTPUT.sql
"""

from __future__ import annotations

import hashlib
import json
import sys
from collections import Counter
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
NAMES_PATH = SCRIPT_DIR / "data" / "japanese_set_names.json"
JA_PREFIX = "ja-"


def sql_text(value: str | None) -> str:
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def load_entries(path: Path = NAMES_PATH) -> list[dict]:
    entries = json.loads(path.read_text(encoding="utf-8"))["sets"]
    codes = [e["code"] for e in entries]
    if len(codes) != len(set(codes)):
        raise ValueError("duplicate codes in the name table")
    owners = {e["set_id"] for e in entries if e["set_id"] in (e["code"], JA_PREFIX + e["code"])}
    for e in entries:
        if e["set_id"] not in owners:
            raise ValueError(f"{e['code']} maps to {e['set_id']}, which no code owns")
        if not e["name"] or not e["series"]:
            raise ValueError(f"{e['code']} has no name or series")
    return sorted(entries, key=lambda e: e["code"])


def owns_set(entry: dict) -> bool:
    return entry["set_id"] in (entry["code"], JA_PREFIX + entry["code"])


def build_sql(entries: list[dict], source_sha256: str) -> str:
    total_cards = sum(e["cards"] for e in entries)
    moved = [e for e in entries if e["set_id"] != e["code"]]
    moved_cards = sum(e["cards"] for e in moved)
    folded = [e for e in moved if not e["set_id"].startswith(JA_PREFIX)]
    ja_sets = [e for e in moved if e["set_id"].startswith(JA_PREFIX)]
    owners = [e for e in entries if owns_set(e)]
    cards_per_set = Counter()
    for e in entries:
        cards_per_set[e["set_id"]] += e["cards"]

    values = ",\n".join(
        "  ({code}, {set_id}, {name}, {series}, {release}, {owns}, {cards})".format(
            code=sql_text(e["code"]),
            set_id=sql_text(e["set_id"]),
            name=sql_text(e["name"]),
            series=sql_text(e["series"]),
            release=sql_text(e["release_date"]) + "::date" if e["release_date"] else "NULL",
            owns="true" if owns_set(e) else "false",
            cards=e["cards"],
        )
        for e in entries
    )

    return f"""-- PTCG-db Japanese set names (one-time data change; owner-approved names 2026-09-27).
--
-- GENERATED by scripts/generate_ptcgdb_set_names_sql.py from
-- scripts/data/japanese_set_names.json (sha256 {source_sha256}). Do not edit by hand.
-- Plan: docs/plans/japanese-set-names.md ("Proper fix").
--
-- ptcgdb is not in the weekly push, so these rows change only here. The push script's
-- --include-ptcgdb path reads the same JSON and publishes the same values.
--
-- What it does, in one transaction:
--   1. Upsert {len(owners)} ptcgdb sets: name "{{code}}: {{English name}}", series "Japanese <era>",
--      release date. {len(owners) - len(ja_sets)} existing rows are named; {len(ja_sets)} "ja-*" sets are inserted for codes
--      whose ID an English set owns. English sets are never written (ON CONFLICT ... WHERE
--      sets.origin = 'ptcgdb', plus a precondition).
--   2. Move {moved_cards:,} ptcgdb cards to their published set ID: {len(ja_sets)} codes to "ja-{{code}}",
--      {', '.join(e['code'] + ' -> ' + e['set_id'] for e in folded)} ({sum(e['cards'] for e in folded)} cards).
--      Card IDs do not change (ptcgdb-sv9-40 stays).
--   3. Set set_name / set_series on all {total_cards:,} ptcgdb cards from their set.
--   4. Check (abort on any mismatch) and refresh explore_filter_options.
-- Idempotent: a second run changes nothing and passes the same checks.
--
-- Expected on the first run: sets upsert {len(owners)} rows; card move {moved_cards:,}; set_name fill {total_cards:,}.
--
-- Undo (exact; checked 2026-09-27: every ptcgdb card's lower(raw_data->>'set_name') equals
-- its original set_id, ptcgdb sets had series/release_date NULL and name = upper(id)):
--   BEGIN;
--   UPDATE public.cards SET set_id = lower(raw_data->>'set_name'), set_name = NULL, set_series = NULL
--    WHERE origin = 'ptcgdb';
--   DELETE FROM public.sets WHERE origin = 'ptcgdb' AND id LIKE 'ja-%';
--   UPDATE public.sets SET name = upper(id), series = NULL, release_date = NULL WHERE origin = 'ptcgdb';
--   SELECT public.refresh_explore_filter_options();
--   COMMIT;

BEGIN;

CREATE TEMP TABLE ptcgdb_set_names (
  code         text PRIMARY KEY,
  set_id       text NOT NULL,
  name         text NOT NULL,
  series       text NOT NULL,
  release_date date,
  owns_set     boolean NOT NULL,
  cards        integer NOT NULL
) ON COMMIT DROP;

INSERT INTO ptcgdb_set_names (code, set_id, name, series, release_date, owns_set, cards) VALUES
{values};

-- Preconditions
DO $$
DECLARE n integer;
BEGIN
  SELECT count(*) INTO n FROM ptcgdb_set_names;
  IF n <> {len(entries)} THEN RAISE EXCEPTION 'name table has % codes, expected {len(entries)}', n; END IF;

  SELECT count(*) INTO n FROM public.cards c
   WHERE c.origin = 'ptcgdb'
     AND NOT EXISTS (SELECT 1 FROM ptcgdb_set_names j WHERE c.set_id IN (j.code, j.set_id));
  IF n <> 0 THEN RAISE EXCEPTION '% ptcgdb cards are on a set the name table does not know', n; END IF;

  SELECT count(*) INTO n FROM public.sets s JOIN ptcgdb_set_names j ON j.owns_set AND s.id = j.set_id
   WHERE s.origin <> 'ptcgdb';
  IF n <> 0 THEN RAISE EXCEPTION '% published ptcgdb set IDs belong to another origin', n; END IF;
END $$;

-- 1. Name the ptcgdb sets; insert the ja-* sets.
INSERT INTO public.sets (id, name, series, release_date, origin)
SELECT set_id, name, series, release_date, 'ptcgdb'
  FROM ptcgdb_set_names
 WHERE owns_set
ON CONFLICT (id) DO UPDATE
   SET name = EXCLUDED.name,
       series = EXCLUDED.series,
       release_date = EXCLUDED.release_date
 WHERE public.sets.origin = 'ptcgdb';

-- 2. Move cards whose code is published under another set ID (card IDs unchanged).
UPDATE public.cards c
   SET set_id = j.set_id
  FROM ptcgdb_set_names j
 WHERE c.origin = 'ptcgdb'
   AND c.set_id = j.code
   AND j.set_id <> j.code;

-- 3. Card set name and series from the published set.
UPDATE public.cards c
   SET set_name = s.name,
       set_series = s.series
  FROM public.sets s
 WHERE c.origin = 'ptcgdb'
   AND s.id = c.set_id
   AND s.origin = 'ptcgdb'
   AND (c.set_name, c.set_series) IS DISTINCT FROM (s.name, s.series);

-- 4. Checks (any failure rolls everything back).
DO $$
DECLARE n integer;
BEGIN
  SELECT count(*) INTO n FROM public.cards WHERE origin = 'ptcgdb';
  IF n <> {total_cards} THEN RAISE EXCEPTION 'ptcgdb card count is %, expected {total_cards}', n; END IF;

  SELECT count(*) INTO n FROM public.cards WHERE origin = 'ptcgdb' AND (set_name IS NULL OR set_series IS NULL);
  IF n <> 0 THEN RAISE EXCEPTION '% ptcgdb cards still have no set name or series', n; END IF;

  SELECT count(*) INTO n FROM public.cards c LEFT JOIN public.sets s ON s.id = c.set_id
   WHERE c.origin = 'ptcgdb' AND s.origin IS DISTINCT FROM 'ptcgdb';
  IF n <> 0 THEN RAISE EXCEPTION '% ptcgdb cards are on a set another origin owns', n; END IF;

  SELECT count(*) INTO n FROM public.cards c
   WHERE c.origin = 'ptcgdb'
     AND NOT EXISTS (SELECT 1 FROM ptcgdb_set_names j
                      WHERE j.set_id = c.set_id AND j.code = lower(c.raw_data->>'set_name'));
  IF n <> 0 THEN RAISE EXCEPTION '% ptcgdb cards are not on the set their code maps to', n; END IF;

  SELECT count(*) INTO n FROM (
    SELECT j.set_id, sum(j.cards) AS expected FROM ptcgdb_set_names j GROUP BY j.set_id
  ) e
  LEFT JOIN (
    SELECT set_id, count(*) AS actual FROM public.cards WHERE origin = 'ptcgdb' GROUP BY set_id
  ) a ON a.set_id = e.set_id
  WHERE a.actual IS DISTINCT FROM e.expected;
  IF n <> 0 THEN RAISE EXCEPTION '% ptcgdb sets have a card count other than the name table''s', n; END IF;

  SELECT count(*) INTO n FROM public.sets s JOIN ptcgdb_set_names j ON j.owns_set AND s.id = j.set_id
   WHERE s.origin = 'ptcgdb' AND s.name = j.name AND s.series = j.series
     AND s.release_date IS NOT DISTINCT FROM j.release_date;
  IF n <> {len(owners)} THEN RAISE EXCEPTION 'only % of {len(owners)} ptcgdb sets carry the reviewed name', n; END IF;
END $$;

SELECT public.refresh_explore_filter_options();

COMMIT;
"""


def main() -> None:
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        sys.exit(2)
    raw = NAMES_PATH.read_bytes()
    sql = build_sql(load_entries(), hashlib.sha256(raw).hexdigest())
    Path(sys.argv[1]).write_text(sql, encoding="utf-8")
    print(f"Wrote {sys.argv[1]}")


if __name__ == "__main__":
    main()
