-- PTCG-db Japanese set names (one-time data change; owner-approved names 2026-09-27).
--
-- GENERATED by scripts/generate_ptcgdb_set_names_sql.py from
-- scripts/data/japanese_set_names.json (sha256 f588d8de32198c571e755539e9f8dbdb7c6906377bde297a966efed28a03ad97). Do not edit by hand.
-- Plan: docs/plans/japanese-set-names.md ("Proper fix").
--
-- ptcgdb is not in the weekly push, so these rows change only here. The push script's
-- --include-ptcgdb path reads the same JSON and publishes the same values.
--
-- What it does, in one transaction:
--   1. Upsert 312 ptcgdb sets: name "{code}: {English name}", series "Japanese <era>",
--      release date. 285 existing rows are named; 27 "ja-*" sets are inserted for codes
--      whose ID an English set owns. English sets are never written (ON CONFLICT ... WHERE
--      sets.origin = 'ptcgdb', plus a precondition).
--   2. Move 3,545 ptcgdb cards to their published set ID: 27 codes to "ja-{code}",
--      xy6 -> xy6-b, xy7 -> xy7-b (22 cards).
--      Card IDs do not change (ptcgdb-sv9-40 stays).
--   3. Set set_name / set_series on all 19,705 ptcgdb cards from their set.
--   4. Check (abort on any mismatch) and refresh explore_filter_options.
-- Idempotent: a second run changes nothing and passes the same checks.
--
-- Expected on the first run: sets upsert 312 rows; card move 3,545; set_name fill 19,705.
--
-- Undo (exact; checked 2026-09-27: every ptcgdb card's lower(raw_data->>'set_name') equals
-- its original set_id, ptcgdb sets had series/release_date NULL and name = upper(id)):
--   BEGIN;
--   UPDATE public.cards SET set_id = lower(raw_data->>'set_name'), set_name = NULL, set_series = NULL
--    WHERE origin = 'ptcgdb';
--   DELETE FROM public.sets WHERE origin = 'ptcgdb' AND id LIKE 'ja-%';
--   UPDATE public.sets SET name = upper(id), series = NULL, release_date = NULL WHERE origin = 'ptcgdb';
--   SELECT public.refresh_explore_filter_options();
--   COMMIT;

BEGIN;

CREATE TEMP TABLE ptcgdb_set_names (
  code         text PRIMARY KEY,
  set_id       text NOT NULL,
  name         text NOT NULL,
  series       text NOT NULL,
  release_date date,
  owns_set     boolean NOT NULL,
  cards        integer NOT NULL
) ON COMMIT DROP;

INSERT INTO ptcgdb_set_names (code, set_id, name, series, release_date, owns_set, cards) VALUES
  ('20th', '20th', '20th: BREAK Starter Pack', 'Japanese XY', '2016-02-27'::date, true, 78),
  ('bb', 'bb', 'Bb: Battle Starter Deck (Magmortar)', 'Japanese HeartGold & SoulSilver', '2009-11-20'::date, true, 9),
  ('bd', 'bd', 'Bd: Battle Starter Deck (Torterra)', 'Japanese HeartGold & SoulSilver', '2009-11-20'::date, true, 10),
  ('bgst', 'bgst', 'BGSt: Battle Gift Set: Thundurus vs Tornadus (Tornadus Deck)', 'Japanese Black & White', NULL, true, 14),
  ('bgsv', 'bgsv', 'BGSv: Battle Gift Set: Thundurus vs Tornadus (Thundurus Deck)', 'Japanese Black & White', NULL, true, 14),
  ('bk', 'bk', 'Bk: Battle Starter Deck (Blastoise)', 'Japanese HeartGold & SoulSilver', '2009-11-20'::date, true, 10),
  ('bkb', 'bkb', 'BKB: Black Kyurem-EX Battle Strength Deck', 'Japanese Black & White', '2012-10-19'::date, true, 19),
  ('bkc', 'bkc', 'BKc: Cobalion Battle Strength Deck', 'Japanese Black & White', '2011-03-18'::date, true, 14),
  ('bkr', 'bkr', 'BKR: Reshiram-EX Battle Strength Deck', 'Japanese Black & White', '2011-10-21'::date, true, 19),
  ('bkt', 'bkt', 'BKt: Terrakion Battle Strength Deck', 'Japanese Black & White', '2011-03-18'::date, true, 14),
  ('bkv', 'bkv', 'BKv: Virizion Battle Strength Deck', 'Japanese Black & White', '2011-03-18'::date, true, 14),
  ('bkw', 'bkw', 'BKW: White Kyurem-EX Battle Strength Deck', 'Japanese Black & White', '2012-10-19'::date, true, 19),
  ('bkz', 'bkz', 'BKZ: Zekrom-EX Battle Strength Deck', 'Japanese Black & White', '2011-10-21'::date, true, 19),
  ('br', 'br', 'Br: Battle Starter Deck (Raichu)', 'Japanese HeartGold & SoulSilver', '2009-11-20'::date, true, 11),
  ('btv', 'btv', 'BTV: Battle Theme Deck: Victini', 'Japanese Black & White', '2011-06-17'::date, true, 22),
  ('bw', 'bw', 'BW: Extra Regulation Box', 'Japanese Sun & Moon', '2019-10-04'::date, true, 12),
  ('bw1-bb', 'bw1-bb', 'BW1-Bb: Black Collection', 'Japanese Black & White', '2010-12-17'::date, true, 53),
  ('bw1-bw', 'bw1-bw', 'BW1-Bw: White Collection', 'Japanese Black & White', '2010-12-17'::date, true, 53),
  ('bw10-b', 'bw10-b', 'BW10-B: EX Battle Boost', 'Japanese Black & White', '2013-07-13'::date, true, 93),
  ('bw2-b', 'bw2-b', 'BW2-B: Red Collection', 'Japanese Black & White', '2011-07-15'::date, true, 66),
  ('bw3-bh', 'bw3-bh', 'BW3-Bh: Hail Blizzard', 'Japanese Black & White', '2011-09-16'::date, true, 52),
  ('bw3-bp', 'bw3-bp', 'BW3-Bp: Psycho Drive', 'Japanese Black & White', '2011-09-16'::date, true, 52),
  ('bw4-b', 'bw4-b', 'BW4-B: Dark Rush', 'Japanese Black & White', '2011-12-16'::date, true, 69),
  ('bw5-brn', 'bw5-brn', 'BW5-Brn: Dragon Blade', 'Japanese Black & White', '2012-03-16'::date, true, 50),
  ('bw5-brz', 'bw5-brz', 'BW5-Brz: Dragon Blast', 'Japanese Black & White', '2012-03-16'::date, true, 50),
  ('bw6-bc', 'bw6-bc', 'BW6-Bc: Cold Flare', 'Japanese Black & White', '2012-07-13'::date, true, 59),
  ('bw6-bf', 'bw6-bf', 'BW6-Bf: Freeze Bolt', 'Japanese Black & White', '2012-07-13'::date, true, 59),
  ('bw7-b', 'bw7-b', 'BW7-B: Plasma Gale', 'Japanese Black & White', '2012-09-14'::date, true, 70),
  ('bw8-brf', 'bw8-brf', 'BW8-Brf: Spiral Force', 'Japanese Black & White', '2012-12-14'::date, true, 51),
  ('bw8-brn', 'bw8-brn', 'BW8-Brn: Thunder Knuckle', 'Japanese Black & White', '2012-12-14'::date, true, 51),
  ('bw9-b', 'bw9-b', 'BW9-B: Megalo Cannon', 'Japanese Black & White', '2013-03-15'::date, true, 76),
  ('bwp', 'ja-bwp', 'BWP: BW-P Promotional cards', 'Japanese Black & White', '2010-12-01'::date, true, 230),
  ('clf', 'clf', 'CLF: Pokemon TCG Classic: Venusaur', 'Japanese Scarlet & Violet', '2023-02-27'::date, true, 1),
  ('clk', 'clk', 'CLK: Pokemon TCG Classic: Blastoise', 'Japanese Scarlet & Violet', '2023-02-27'::date, true, 1),
  ('cll', 'cll', 'CLL: Pokemon TCG Classic: Charizard', 'Japanese Scarlet & Violet', '2023-02-27'::date, true, 1),
  ('cp1', 'cp1', 'CP1: Magma Gang vs Aqua Gang: Double Crisis', 'Japanese XY', '2015-01-30'::date, true, 34),
  ('cp2', 'cp2', 'CP2: Legendary Shine Collection', 'Japanese XY', '2015-07-18'::date, true, 27),
  ('cp3', 'cp3', 'CP3: PokeKyun Collection', 'Japanese XY', '2016-01-29'::date, true, 32),
  ('cp4', 'cp4', 'CP4: Premium Champion Pack', 'Japanese XY', '2016-04-16'::date, true, 132),
  ('cp5', 'cp5', 'CP5: Mythical & Legendary Dream Shine Collection', 'Japanese XY', '2016-07-16'::date, true, 38),
  ('cp6', 'cp6', 'CP6: Expansion Pack 20th Anniversary', 'Japanese XY', '2016-09-16'::date, true, 103),
  ('cpm', 'cpm', 'CPm: Mewtwo LV.X Collection Pack', 'Japanese Platinum', '2009-04-18'::date, true, 12),
  ('cpr', 'cpr', 'CPr: Regigigas LV.X Collection Pack', 'Japanese Platinum', '2009-04-18'::date, true, 12),
  ('cps', 'cps', 'CPs: Shaymin LV.X Collection Pack', 'Japanese Platinum', '2009-04-18'::date, true, 12),
  ('cs1m', 'cs1m', 'CS1m: Journey Partners Collection Sheet (Oshawott)', 'Japanese Black & White', NULL, true, 3),
  ('cs1p', 'cs1p', 'CS1p: Journey Partners Collection Sheet (Tepig)', 'Japanese Black & White', NULL, true, 3),
  ('cs1t', 'cs1t', 'CS1t: Journey Partners Collection Sheet (Snivy)', 'Japanese Black & White', NULL, true, 3),
  ('dp1', 'ja-dp1', 'DP1: Space-Time Creation', 'Japanese Diamond & Pearl', '2006-11-30'::date, true, 105),
  ('dp2', 'ja-dp2', 'DP2: Secret of the Lakes', 'Japanese Diamond & Pearl', '2007-03-02'::date, true, 106),
  ('dp3', 'ja-dp3', 'DP3: Shining Darkness', 'Japanese Diamond & Pearl', '2007-07-05'::date, true, 111),
  ('dp4', 'ja-dp4', 'DP4: Dawn Dash / Moonlit Pursuit', 'Japanese Diamond & Pearl', NULL, true, 114),
  ('dp5', 'ja-dp5', 'DP5: Cry from the Mysterious / Temple of Anger', 'Japanese Diamond & Pearl', NULL, true, 100),
  ('dpp', 'ja-dpp', 'DPP: DP-P Promotional cards', 'Japanese Diamond & Pearl', '2006-12-01'::date, true, 128),
  ('dps-b', 'dps-b', 'DPs-B: Intense Fight in the Destroyed Sky', 'Japanese Diamond & Pearl', '2008-07-10'::date, true, 92),
  ('dps-sd', 'dps-sd', 'DPs-Sd: Giratina vs Dialga Deck Kit (Dialga)', 'Japanese Diamond & Pearl', '2008-07-10'::date, true, 14),
  ('dps-sg', 'dps-sg', 'DPs-Sg: Giratina vs Dialga Deck Kit (Giratina)', 'Japanese Diamond & Pearl', '2008-07-10'::date, true, 14),
  ('dpt-epd', 'dpt-epd', 'DPt-EPd: Entry Pack DPt (Dialga)', 'Japanese Platinum', '2008-10-10'::date, true, 13),
  ('dpt-epg', 'dpt-epg', 'DPt-EPg: Entry Pack DPt (Giratina)', 'Japanese Platinum', '2008-10-10'::date, true, 13),
  ('dpt-epp', 'dpt-epp', 'DPt-EPp: Entry Pack DPt (Palkia)', 'Japanese Platinum', '2008-10-10'::date, true, 13),
  ('dpt-gbhi', 'dpt-gbhi', 'DPt-GBhi: DPt Gift Box (Chimchar)', 'Japanese Platinum', '2008-11-20'::date, true, 13),
  ('dpt-gbna', 'dpt-gbna', 'DPt-GBna: DPt Gift Box (Turtwig)', 'Japanese Platinum', '2008-11-20'::date, true, 14),
  ('dpt-gbpi', 'dpt-gbpi', 'DPt-GBpi: DPt Gift Box (Pikachu)', 'Japanese Platinum', '2008-11-20'::date, true, 15),
  ('dpt-gbpo', 'dpt-gbpo', 'DPt-GBpo: DPt Gift Box (Piplup)', 'Japanese Platinum', '2008-11-20'::date, true, 15),
  ('dpt-mrp09', 'dpt-mrp09', 'DPt-MRP09: Movie Commemoration Random Pack', 'Japanese Platinum', '2009-07-18'::date, true, 22),
  ('dpt1-b', 'dpt1-b', 'DPt1-B: Galactic''s Conquest', 'Japanese Platinum', '2008-10-10'::date, true, 96),
  ('dpt2-b', 'dpt2-b', 'DPt2-B: Bonds to the End of Time', 'Japanese Platinum', '2008-12-26'::date, true, 90),
  ('dpt2-se', 'dpt2-se', 'DPt2-Se: Infernape vs Gallade SP Deck Kit (Gallade)', 'Japanese Platinum', '2008-12-26'::date, true, 18),
  ('dpt2-sg', 'dpt2-sg', 'DPt2-Sg: Infernape vs Gallade SP Deck Kit (Infernape)', 'Japanese Platinum', '2008-12-26'::date, true, 18),
  ('dpt3-b', 'dpt3-b', 'DPt3-B: Beat of the Frontier', 'Japanese Platinum', '2009-03-06'::date, true, 100),
  ('dpt3-sg', 'dpt3-sg', 'DPt3-Sg: Garchomp vs Charizard SP Deck Kit (Garchomp)', 'Japanese Platinum', '2008-12-26'::date, true, 16),
  ('dpt3-sl', 'dpt3-sl', 'DPt3-Sl: Garchomp vs Charizard SP Deck Kit (Charizard)', 'Japanese Platinum', '2008-12-26'::date, true, 16),
  ('dpt4-b', 'dpt4-b', 'DPt4-B: Advent of Arceus', 'Japanese Platinum', '2009-07-08'::date, true, 90),
  ('dpt4-sgf', 'dpt4-sgf', 'DPt4-Sgf: Arceus LV.X Deck: Grass & Fire', 'Japanese Platinum', '2009-07-08'::date, true, 17),
  ('dpt4-slp', 'dpt4-slp', 'DPt4-Slp: Arceus LV.X Deck: Lightning & Psychic', 'Japanese Platinum', '2009-07-08'::date, true, 17),
  ('dptp', 'dptp', 'DPtP: DPt-P Promotional cards', 'Japanese Platinum', '2008-10-01'::date, true, 52),
  ('ds', 'ds', 'DS: Dragon Selection', 'Japanese Black & White', '2012-01-27'::date, true, 20),
  ('el', 'el', 'El: Leafeon vs Metagross Expert Deck (Leafeon)', 'Japanese HeartGold & SoulSilver', '2009-11-20'::date, true, 15),
  ('em', 'em', 'Em: Leafeon vs Metagross Expert Deck (Metagross)', 'Japanese HeartGold & SoulSilver', '2009-11-20'::date, true, 14),
  ('ep08', 'ep08', 'EP08: Entry Pack ''08', 'Japanese Diamond & Pearl', '2007-11-30'::date, true, 1),
  ('gbr', 'gbr', 'GBR: Garchomp Half Deck', 'Japanese Black & White', '2012-03-16'::date, true, 16),
  ('hsm', 'hsm', 'HSm: BW Beginning Set (Oshawott Deck)', 'Japanese Black & White', NULL, true, 16),
  ('hsp', 'ja-hsp', 'HSp: BW Beginning Set (Tepig Deck)', 'Japanese Black & White', NULL, true, 16),
  ('hspm', 'hspm', 'HSPm: BW Beginning Set Pikachu Ver. (Oshawott Deck)', 'Japanese Black & White', NULL, true, 15),
  ('hspp', 'hspp', 'HSPp: BW Beginning Set Pikachu Ver. (Tepig Deck)', 'Japanese Black & White', NULL, true, 15),
  ('hspt', 'hspt', 'HSPt: BW Beginning Set Pikachu Ver. (Snivy Deck)', 'Japanese Black & White', NULL, true, 15),
  ('hst', 'hst', 'HSt: BW Beginning Set (Snivy Deck)', 'Japanese Black & White', NULL, true, 16),
  ('hszm', 'hszm', 'HSZm: National Beginning Set (Oshawott Deck)', 'Japanese Black & White', NULL, true, 15),
  ('hszp', 'hszp', 'HSZp: National Beginning Set (Tepig Deck)', 'Japanese Black & White', NULL, true, 15),
  ('hszt', 'hszt', 'HSZt: National Beginning Set (Snivy Deck)', 'Japanese Black & White', NULL, true, 15),
  ('hxy', 'hxy', 'HXY: XY Beginning Set', 'Japanese XY', '2013-11-08'::date, true, 40),
  ('kk', 'kk', 'KK: Blastoise + Kyurem-EX Combo Deck', 'Japanese Black & White', '2013-03-15'::date, true, 19),
  ('kld', 'kld', 'KLD: Keldeo Battle Strength Deck', 'Japanese Black & White', '2012-04-20'::date, true, 16),
  ('l1-bhg', 'l1-bhg', 'L1-Bhg: HeartGold Collection', 'Japanese HeartGold & SoulSilver', '2009-10-09'::date, true, 69),
  ('l1-bss', 'l1-bss', 'L1-Bss: SoulSilver Collection', 'Japanese HeartGold & SoulSilver', '2009-10-09'::date, true, 69),
  ('l2-b', 'l2-b', 'L2-B: Revival Legends', 'Japanese HeartGold & SoulSilver', '2010-02-11'::date, true, 77),
  ('l2-sb', 'l2-sb', 'L2-Sb: Tyranitar Constructed Standard Deck', 'Japanese HeartGold & SoulSilver', '2010-02-11'::date, true, 19),
  ('l2-sh', 'l2-sh', 'L2-Sh: Steelix Constructed Standard Deck', 'Japanese HeartGold & SoulSilver', '2010-02-11'::date, true, 19),
  ('l3-b', 'l3-b', 'L3-B: Clash at the Summit', 'Japanese HeartGold & SoulSilver', '2010-07-08'::date, true, 77),
  ('ll', 'll', 'LL: Lost Link', 'Japanese HeartGold & SoulSilver', '2010-04-16'::date, true, 39),
  ('lp', 'lp', 'LP: Legends Promos', 'Japanese HeartGold & SoulSilver', '2009-09-01'::date, true, 80),
  ('m-p', 'm-p', 'M-P: M-P Promotional Cards', 'Japanese Mega Evolution', '2025-08-08'::date, true, 13),
  ('m1l', 'm1l', 'M1L: Mega Brave', 'Japanese Mega Evolution', '2025-08-01'::date, true, 63),
  ('m1s', 'm1s', 'M1S: Mega Symphonia', 'Japanese Mega Evolution', '2025-08-01'::date, true, 63),
  ('ma', 'ma', 'MA: Premium Trainer Box MEGA', 'Japanese Mega Evolution', NULL, true, 43),
  ('mbd', 'mbd', 'MBD: MEGA Starter Set Mega Diancie ex', 'Japanese Mega Evolution', '2025-09-05'::date, true, 22),
  ('mbg', 'mbg', 'MBG: MEGA Starter Set Mega Gengar ex', 'Japanese Mega Evolution', '2025-09-12'::date, true, 22),
  ('mdb', 'mdb', 'MDB: Master Deck Build Box EX', 'Japanese Black & White', '2012-09-14'::date, true, 47),
  ('mg', 'mg', 'MG: Mewtwo vs Genesect Deck Kit', 'Japanese Black & White', NULL, true, 17),
  ('mmb-p', 'mmb-p', 'MMB-P: M Master Deck Build Box Power Style', 'Japanese XY', '2015-08-07'::date, true, 50),
  ('mmb-s', 'mmb-s', 'MMB-S: M Master Deck Build Box Speed Style', 'Japanese XY', '2015-08-07'::date, true, 50),
  ('mps', 'mps', 'MPS: 10th Movie Commemoration Premium Sheet', 'Japanese Diamond & Pearl', NULL, true, 1),
  ('mps08', 'mps08', 'MPS08: Movie Commemoration Premium Sheet 2008', 'Japanese Diamond & Pearl', NULL, true, 9),
  ('pbg', 'pbg', 'PBG: Team Plasma Battle Gift Set', 'Japanese Black & White', '2012-11-16'::date, true, 17),
  ('ppd', 'ppd', 'PPD: Team Plasma''s Powered Half Deck', 'Japanese Black & White', '2012-09-14'::date, true, 18),
  ('ppp', 'ppp', 'PPP: PPP Promotional cards', 'Japanese Diamond & Pearl', '2007-05-01'::date, true, 7),
  ('pw', 'pw', 'PW: Pikachu World (7-Eleven / Pokémon Center Original)', 'Japanese HeartGold & SoulSilver', NULL, true, 1),
  ('ran', 'ran', 'Ran: Melee! Pokemon Scramble', 'Japanese Platinum', '2009-07-10'::date, true, 19),
  ('s-p', 's-p', 'S-P: Sword & Shield Promos', 'Japanese Sword & Shield', '2019-11-01'::date, true, 318),
  ('s10a', 's10a', 'S10a: Dark Phantasma', 'Japanese Sword & Shield', '2022-05-13'::date, true, 99),
  ('s10b', 's10b', 'S10b: Pokemon GO', 'Japanese Sword & Shield', '2022-06-17'::date, true, 94),
  ('s10d', 's10d', 'S10D: Time Gazer', 'Japanese Sword & Shield', '2022-04-08'::date, true, 88),
  ('s10p', 's10p', 'S10P: Space Juggler', 'Japanese Sword & Shield', '2022-04-08'::date, true, 88),
  ('s11', 's11', 'S11: Lost Abyss', 'Japanese Sword & Shield', '2022-07-15'::date, true, 127),
  ('s11a', 's11a', 'S11a: Incandescent Arcana', 'Japanese Sword & Shield', '2022-09-02'::date, true, 94),
  ('s12', 's12', 'S12: Paradigm Trigger', 'Japanese Sword & Shield', '2022-10-21'::date, true, 125),
  ('s12a', 's12a', 'S12a: VSTAR Universe', 'Japanese Sword & Shield', '2022-12-02'::date, true, 255),
  ('s1a', 's1a', 'S1a: VMAX Rising', 'Japanese Sword & Shield', '2020-02-07'::date, true, 78),
  ('s1h', 's1h', 'S1H: Shield', 'Japanese Sword & Shield', '2019-12-06'::date, true, 68),
  ('s1w', 's1w', 'S1W: Sword', 'Japanese Sword & Shield', '2019-12-06'::date, true, 68),
  ('s2', 's2', 'S2: Rebellion Crash', 'Japanese Sword & Shield', '2020-03-06'::date, true, 106),
  ('s2a', 's2a', 'S2a: Explosive Walker', 'Japanese Sword & Shield', '2020-04-24'::date, true, 78),
  ('s3', 's3', 'S3: Infinity Zone', 'Japanese Sword & Shield', '2020-06-05'::date, true, 110),
  ('s3a', 's3a', 'S3a: Legendary Heartbeat', 'Japanese Sword & Shield', '2020-07-10'::date, true, 85),
  ('s4', 's4', 'S4: Amazing Volt Tackle', 'Japanese Sword & Shield', '2020-09-18'::date, true, 111),
  ('s4a', 's4a', 'S4a: Shiny Star V', 'Japanese Sword & Shield', '2020-11-20'::date, true, 326),
  ('s5a', 's5a', 'S5a: Peerless Fighters', 'Japanese Sword & Shield', '2021-03-19'::date, true, 84),
  ('s5i', 's5i', 'S5I: Single Strike Master', 'Japanese Sword & Shield', '2021-01-22'::date, true, 81),
  ('s5r', 's5r', 'S5R: Rapid Strike Master', 'Japanese Sword & Shield', '2021-01-22'::date, true, 81),
  ('s6a', 's6a', 'S6a: Eevee Heroes', 'Japanese Sword & Shield', '2021-05-28'::date, true, 87),
  ('s6h', 's6h', 'S6H: Silver Lance', 'Japanese Sword & Shield', '2021-04-23'::date, true, 83),
  ('s6k', 's6k', 'S6K: Jet-Black Spirit', 'Japanese Sword & Shield', '2021-04-23'::date, true, 83),
  ('s7d', 's7d', 'S7D: Skyscraping Perfection', 'Japanese Sword & Shield', '2021-07-09'::date, true, 79),
  ('s7r', 's7r', 'S7R: Blue Sky Stream', 'Japanese Sword & Shield', '2021-07-09'::date, true, 79),
  ('s8', 's8', 'S8: Fusion Arts', 'Japanese Sword & Shield', '2021-09-24'::date, true, 115),
  ('s8a', 's8a', 'S8a: 25th Anniversary Collection', 'Japanese Sword & Shield', '2021-10-22'::date, true, 27),
  ('s8a-g', 's8a-g', 'S8a-G: 25th Anniversary Golden Box', 'Japanese Sword & Shield', '2021-12-01'::date, true, 16),
  ('s8b', 's8b', 'S8b: VMAX Climax', 'Japanese Sword & Shield', '2021-12-03'::date, true, 272),
  ('s9', 's9', 'S9: Star Birth', 'Japanese Sword & Shield', '2022-01-14'::date, true, 127),
  ('s9a', 's9a', 'S9a: Battle Region', 'Japanese Sword & Shield', '2022-02-25'::date, true, 93),
  ('sa', 'sa', 'SA: Starter Set V', 'Japanese Sword & Shield', NULL, true, 29),
  ('sb', 'sb', 'SB: Sword & Shield Premium Trainer Box', 'Japanese Sword & Shield', '2019-12-06'::date, true, 24),
  ('sc', 'sc', 'SC: Shiny Collection', 'Japanese Black & White', '2013-02-01'::date, true, 20),
  ('sc2', 'sc2', 'SC2: Charizard Starter Set VMAX 2', 'Japanese Sword & Shield', '2020-12-04'::date, true, 21),
  ('scs', 'scs', 'SCS: Grimmsnarl Starter Set VMAX', 'Japanese Sword & Shield', '2020-03-27'::date, true, 21),
  ('sd', 'sd', 'SD: V Starter Decks', 'Japanese Sword & Shield', '2020-07-10'::date, true, 127),
  ('sef', 'sef', 'SEF: Venusaur Starter Set VMAX', 'Japanese Sword & Shield', '2020-12-04'::date, true, 21),
  ('sek', 'sek', 'SEK: Blastoise Starter Set VMAX', 'Japanese Sword & Shield', '2020-12-04'::date, true, 20),
  ('sf', 'sf', 'SF: Single Strike & Rapid Strike Premium Trainer Boxes', 'Japanese Sword & Shield', '2021-01-22'::date, true, 33),
  ('sgg', 'sgg', 'SGG: Gengar VMAX High-Class Deck', 'Japanese Sword & Shield', '2021-07-07'::date, true, 21),
  ('sgi', 'sgi', 'SGI: Inteleon VMAX High-Class Deck', 'Japanese Sword & Shield', '2021-07-07'::date, true, 24),
  ('sh', 'sh', 'SH: Sword & Shield Family Pokemon Card Game', 'Japanese Sword & Shield', '2021-07-09'::date, true, 59),
  ('si', 'si', 'SI: Start Deck 100', 'Japanese Sword & Shield', '2021-12-17'::date, true, 428),
  ('sj', 'sj', 'SJ: Zacian & Zamazenta vs Eternatus Special Deck Set', 'Japanese Sword & Shield', '2021-11-05'::date, true, 30),
  ('sk', 'sk', 'SK: VSTAR Premium Trainer Box', 'Japanese Sword & Shield', '2022-01-14'::date, true, 30),
  ('sld', 'sld', 'SLD: Darkrai Starter Set VSTAR', 'Japanese Sword & Shield', '2022-02-25'::date, true, 21),
  ('sll', 'sll', 'SLL: Lucario Starter Set VSTAR', 'Japanese Sword & Shield', '2022-02-25'::date, true, 22),
  ('sm-xy', 'sm-xy', 'SM-XY: Premium Trainer Box (XY-era reprints)', 'Japanese Sun & Moon', NULL, true, 12),
  ('sm0', 'sm0', 'SM0: Pikachu''s New Friends', 'Japanese Sun & Moon', '2016-11-18'::date, true, 4),
  ('sm10', 'ja-sm10', 'SM10: Double Blaze', 'Japanese Sun & Moon', '2019-03-01'::date, true, 107),
  ('sm10a', 'sm10a', 'SM10a: GG End', 'Japanese Sun & Moon', '2019-04-05'::date, true, 62),
  ('sm10b', 'sm10b', 'SM10b: Sky Legend', 'Japanese Sun & Moon', '2019-04-26'::date, true, 62),
  ('sm11', 'ja-sm11', 'SM11: Miracle Twin', 'Japanese Sun & Moon', '2019-05-31'::date, true, 106),
  ('sm11a', 'sm11a', 'SM11a: Remix Bout', 'Japanese Sun & Moon', '2019-07-05'::date, true, 73),
  ('sm11b', 'sm11b', 'SM11b: Dream League', 'Japanese Sun & Moon', '2019-08-02'::date, true, 68),
  ('sm12', 'ja-sm12', 'SM12: Alter Genesis', 'Japanese Sun & Moon', '2019-09-06'::date, true, 108),
  ('sm12a', 'sm12a', 'SM12a: TAG TEAM GX: Tag All Stars', 'Japanese Sun & Moon', '2019-10-04'::date, true, 210),
  ('sm1m', 'sm1m', 'SM1M: Collection Moon', 'Japanese Sun & Moon', '2016-12-09'::date, true, 66),
  ('sm1p', 'sm1p', 'SM1p: Sun & Moon', 'Japanese Sun & Moon', '2017-01-27'::date, true, 63),
  ('sm1s', 'sm1s', 'SM1S: Collection Sun', 'Japanese Sun & Moon', '2016-12-09'::date, true, 66),
  ('sm2k', 'sm2k', 'SM2K: Islands Await You', 'Japanese Sun & Moon', '2017-03-17'::date, true, 55),
  ('sm2l', 'sm2l', 'SM2L: Alolan Moonlight', 'Japanese Sun & Moon', '2017-03-17'::date, true, 55),
  ('sm2p', 'sm2p', 'SM2p: Facing a New Trial', 'Japanese Sun & Moon', '2017-04-21'::date, true, 61),
  ('sm3h', 'sm3h', 'SM3H: To Have Seen the Battle Rainbow', 'Japanese Sun & Moon', '2017-06-16'::date, true, 57),
  ('sm3n', 'sm3n', 'SM3N: Darkness that Consumes Light', 'Japanese Sun & Moon', '2017-06-16'::date, true, 57),
  ('sm3p', 'sm3p', 'SM3p: Shining Legends', 'Japanese Sun & Moon', '2017-07-15'::date, true, 77),
  ('sm4a', 'sm4a', 'SM4A: Ultradimensional Beasts', 'Japanese Sun & Moon', '2017-09-15'::date, true, 55),
  ('sm4p', 'sm4p', 'SM4p: GX Battle Boost', 'Japanese Sun & Moon', '2017-10-20'::date, true, 120),
  ('sm4s', 'sm4s', 'SM4S: Awakened Heroes', 'Japanese Sun & Moon', '2017-09-15'::date, true, 55),
  ('sm5m', 'sm5m', 'SM5M: Ultra Moon', 'Japanese Sun & Moon', '2017-12-08'::date, true, 72),
  ('sm5p', 'sm5p', 'SM5p: Ultra Force', 'Japanese Sun & Moon', '2018-01-19'::date, true, 56),
  ('sm5s', 'sm5s', 'SM5S: Ultra Sun', 'Japanese Sun & Moon', '2017-12-08'::date, true, 72),
  ('sm6', 'ja-sm6', 'SM6: Forbidden Light', 'Japanese Sun & Moon', '2018-03-02'::date, true, 102),
  ('sm6a', 'sm6a', 'SM6a: Dragon Storm', 'Japanese Sun & Moon', '2018-04-06'::date, true, 59),
  ('sm6b', 'sm6b', 'SM6b: Champion Road', 'Japanese Sun & Moon', '2018-05-30'::date, true, 77),
  ('sm7', 'ja-sm7', 'SM7: Sky-Splitting Charisma', 'Japanese Sun & Moon', '2018-06-01'::date, true, 104),
  ('sm7a', 'sm7a', 'SM7a: Thunderclap Spark', 'Japanese Sun & Moon', '2018-07-06'::date, true, 66),
  ('sm7b', 'sm7b', 'SM7b: Fairy Rise', 'Japanese Sun & Moon', '2018-08-03'::date, true, 56),
  ('sm8', 'ja-sm8', 'SM8: Super-Burst Impact', 'Japanese Sun & Moon', '2018-09-07'::date, true, 103),
  ('sm8a', 'sm8a', 'SM8a: Dark Order', 'Japanese Sun & Moon', '2018-10-05'::date, true, 58),
  ('sm8b', 'sm8b', 'SM8b: GX Ultra Shiny', 'Japanese Sun & Moon', '2018-11-02'::date, true, 243),
  ('sm9', 'ja-sm9', 'SM9: Tag Bolt', 'Japanese Sun & Moon', '2018-12-07'::date, true, 109),
  ('sm9a', 'sm9a', 'SM9a: Night Unison', 'Japanese Sun & Moon', '2019-01-11'::date, true, 63),
  ('sm9b', 'sm9b', 'SM9b: Full Metal Wall', 'Japanese Sun & Moon', '2019-02-01'::date, true, 62),
  ('sma', 'ja-sma', 'SMA: Sun & Moon Starter Set', 'Japanese Sun & Moon', '2016-12-09'::date, true, 68),
  ('smb', 'smb', 'SMB: Premium Trainer Box', 'Japanese Sun & Moon', '2016-12-09'::date, true, 15),
  ('smc', 'smc', 'SMC: Tapu Bulu-GX Enhanced Starter Set', 'Japanese Sun & Moon', '2017-03-17'::date, true, 21),
  ('smd', 'smd', 'SMD: Ash vs Team Rocket Deck Kit', 'Japanese Sun & Moon', '2017-04-21'::date, true, 30),
  ('sme', 'sme', 'SME: Solgaleo-GX & Lunala-GX Legendary Starter Set', 'Japanese Sun & Moon', '2017-11-10'::date, true, 21),
  ('smf', 'smf', 'SMF: Ultra Sun & Ultra Moon Premium Trainer Box', 'Japanese Sun & Moon', '2017-12-08'::date, true, 12),
  ('smg', 'smg', 'SMG: Ultra Sun & Ultra Moon Deck Build Boxes', 'Japanese Sun & Moon', '2018-02-16'::date, true, 12),
  ('smh', 'smh', 'SMH: GX Starter Decks', 'Japanese Sun & Moon', '2018-07-13'::date, true, 131),
  ('smi', 'smi', 'SMI: Flareon-GX, Vaporeon-GX & Jolteon-GX Starter Sets', 'Japanese Sun & Moon', '2018-11-23'::date, true, 38),
  ('smj', 'smj', 'SMJ: Tag Team GX Premium Trainer Box', 'Japanese Sun & Moon', '2018-12-07'::date, true, 35),
  ('smk', 'smk', 'SMK: Trainer Battle Decks', 'Japanese Sun & Moon', '2019-01-25'::date, true, 31),
  ('sml', 'sml', 'SML: Sun & Moon Family Pokemon Card Game', 'Japanese Sun & Moon', '2019-03-15'::date, true, 57),
  ('smm', 'smm', 'SMM: Tag Team GX Starter Sets', 'Japanese Sun & Moon', '2019-05-31'::date, true, 31),
  ('smn', 'smn', 'SMN: Tag Team GX Deck Build Box', 'Japanese Sun & Moon', '2019-03-01'::date, true, 29),
  ('smp', 'ja-smp', 'SMP: Sun & Moon Promos', 'Japanese Sun & Moon', '2016-11-01'::date, true, 410),
  ('smp1', 'smp1', 'SMP1: Rockruff Full Power Deck', 'Japanese Sun & Moon', '2016-12-15'::date, true, 13),
  ('smp2', 'smp2', 'SMP2: Great Detective Pikachu', 'Japanese Sun & Moon', '2019-04-26'::date, true, 25),
  ('sn', 'sn', 'SN: Start Deck 100 CoroCoro Comic Version', 'Japanese Sword & Shield', '2022-03-01'::date, true, 25),
  ('snpo', 'snpo', 'SNPo: Noivern BREAK Evolution Pack', 'Japanese XY', '2015-09-26'::date, true, 10),
  ('snpr', 'snpr', 'SNPr: Raichu BREAK Evolution Pack', 'Japanese XY', '2015-09-26'::date, true, 10),
  ('so', 'so', 'SO: Charizard VSTAR vs Rayquaza VMAX Special Deck Set', 'Japanese Sword & Shield', '2022-11-04'::date, true, 32),
  ('sp1', 'sp1', 'SP1: Zacian + Zamazenta Box', 'Japanese Sword & Shield', '2019-12-27'::date, true, 7),
  ('sp2', 'sp2', 'SP2: VMAX Special Set', 'Japanese Sword & Shield', '2020-10-23'::date, true, 8),
  ('sp3', 'sp3', 'SP3: Silver Lance & Jet-Black Spirit Jumbo Pack Set', 'Japanese Sword & Shield', '2021-04-23'::date, true, 6),
  ('sp4', 'sp4', 'SP4: Eevee Heroes VMAX Special Set', 'Japanese Sword & Shield', '2021-05-28'::date, true, 8),
  ('sp5', 'sp5', 'SP5: V-UNION Special Card Sets', 'Japanese Sword & Shield', '2021-08-20'::date, true, 4),
  ('sp6', 'sp6', 'SP6: VSTAR Special Set', 'Japanese Sword & Shield', '2022-08-05'::date, true, 6),
  ('spd', 'spd', 'SPD: Deoxys VSTAR & VMAX High-Class Deck', 'Japanese Sword & Shield', '2022-07-15'::date, true, 21),
  ('spz', 'spz', 'SPZ: Zeraora VSTAR & VMAX High-Class Deck', 'Japanese Sword & Shield', '2022-07-15'::date, true, 21),
  ('sv-p', 'sv-p', 'SV-P: SV-P Promotional Cards', 'Japanese Scarlet & Violet', '2024-10-18'::date, true, 270),
  ('sv10', 'ja-sv10', 'SV10: The Glory of Team Rocket', 'Japanese Scarlet & Violet', '2025-04-18'::date, true, 132),
  ('sv11b', 'sv11b', 'SV11B: Black Bolt', 'Japanese Scarlet & Violet', '2025-06-06'::date, true, 174),
  ('sv11w', 'sv11w', 'SV11W: White Flare', 'Japanese Scarlet & Violet', '2025-06-06'::date, true, 174),
  ('sv1a', 'sv1a', 'SV1a: Triplet Beat', 'Japanese Scarlet & Violet', '2023-03-10'::date, true, 103),
  ('sv1s', 'sv1s', 'SV1S: Scarlet ex', 'Japanese Scarlet & Violet', '2023-01-20'::date, true, 108),
  ('sv1v', 'sv1v', 'SV1V: Violet ex', 'Japanese Scarlet & Violet', '2023-01-20'::date, true, 108),
  ('sv2a', 'sv2a', 'SV2a: Pokemon Card 151', 'Japanese Scarlet & Violet', '2023-06-16'::date, true, 210),
  ('sv2d', 'sv2d', 'SV2D: Clay Burst', 'Japanese Scarlet & Violet', '2023-04-14'::date, true, 99),
  ('sv2p', 'sv2p', 'SV2P: Snow Hazard', 'Japanese Scarlet & Violet', '2023-04-14'::date, true, 99),
  ('sv3', 'ja-sv3', 'SV3: Ruler of the Black Flame', 'Japanese Scarlet & Violet', '2023-07-28'::date, true, 141),
  ('sv3a', 'sv3a', 'SV3a: Raging Surf', 'Japanese Scarlet & Violet', '2023-09-22'::date, true, 92),
  ('sv4a', 'sv4a', 'SV4a: Shiny Treasure ex', 'Japanese Scarlet & Violet', '2023-12-01'::date, true, 360),
  ('sv4k', 'sv4k', 'SV4K: Ancient Roar', 'Japanese Scarlet & Violet', '2023-10-27'::date, true, 95),
  ('sv4m', 'sv4m', 'SV4M: Future Flash', 'Japanese Scarlet & Violet', '2023-10-27'::date, true, 95),
  ('sv5a', 'sv5a', 'SV5a: Crimson Haze', 'Japanese Scarlet & Violet', '2024-03-22'::date, true, 96),
  ('sv5k', 'sv5k', 'SV5K: Wild Force', 'Japanese Scarlet & Violet', '2024-01-26'::date, true, 100),
  ('sv5m', 'sv5m', 'SV5M: Cyber Judge', 'Japanese Scarlet & Violet', '2024-01-26'::date, true, 100),
  ('sv6', 'ja-sv6', 'SV6: Transformation Mask', 'Japanese Scarlet & Violet', '2024-04-26'::date, true, 133),
  ('sv6a', 'sv6a', 'SV6a: Night Wanderer', 'Japanese Scarlet & Violet', '2024-06-07'::date, true, 94),
  ('sv7', 'ja-sv7', 'SV7: Stellar Miracle', 'Japanese Scarlet & Violet', '2024-07-19'::date, true, 135),
  ('sv7a', 'sv7a', 'SV7a: Paradise Dragona', 'Japanese Scarlet & Violet', '2024-09-13'::date, true, 94),
  ('sv8', 'ja-sv8', 'SV8: Super Electric Breaker', 'Japanese Scarlet & Violet', '2024-10-18'::date, true, 138),
  ('sv8a', 'sv8a', 'SV8a: Terastal Fest ex', 'Japanese Scarlet & Violet', '2024-12-06'::date, true, 237),
  ('sv9', 'ja-sv9', 'SV9: Battle Partners', 'Japanese Scarlet & Violet', '2025-01-24'::date, true, 132),
  ('sv9a', 'sv9a', 'SV9a: Heat Wave Arena', 'Japanese Scarlet & Violet', '2025-03-14'::date, true, 92),
  ('sval', 'sval', 'SVAL: ex Starter Set Fuecoco & Ampharos ex', 'Japanese Scarlet & Violet', '2023-01-20'::date, true, 21),
  ('svam', 'svam', 'SVAM: ex Starter Set Sprigatito & Lucario ex', 'Japanese Scarlet & Violet', '2023-01-20'::date, true, 23),
  ('svaw', 'svaw', 'SVAW: ex Starter Set Quaxly & Mimikyu ex', 'Japanese Scarlet & Violet', '2023-01-20'::date, true, 23),
  ('svb', 'svb', 'SVB: Premium Trainer Box ex', 'Japanese Scarlet & Violet', '2023-01-20'::date, true, 28),
  ('svc', 'svc', 'SVC: ex Starter Set Pikachu ex & Pawmot', 'Japanese Scarlet & Violet', '2023-03-24'::date, true, 21),
  ('svd', 'svd', 'SVD: ex Start Decks', 'Japanese Scarlet & Violet', '2023-07-07'::date, true, 139),
  ('svel', 'svel', 'SVEL: Skeledirge ex Terastal Starter Set', 'Japanese Scarlet & Violet', '2023-09-22'::date, true, 20),
  ('svem', 'svem', 'SVEM: Mewtwo ex Terastal Starter Set', 'Japanese Scarlet & Violet', '2023-09-22'::date, true, 20),
  ('svf', 'svf', 'SVF: Ruler of the Black Flame Deck Build Box', 'Japanese Scarlet & Violet', '2023-07-28'::date, true, 38),
  ('svg', 'svg', 'SVG: Venusaur, Charizard & Blastoise Special Deck Set', 'Japanese Scarlet & Violet', '2023-11-10'::date, true, 52),
  ('svhk', 'svhk', 'SVHK: Ancient Koraidon ex Starter Deck & Build Set', 'Japanese Scarlet & Violet', '2024-01-26'::date, true, 53),
  ('svhm', 'svhm', 'SVHM: Future Miraidon ex Starter Deck & Build Set', 'Japanese Scarlet & Violet', '2024-01-26'::date, true, 53),
  ('svi', 'svi', 'SVI: Battle Academy', 'Japanese Scarlet & Violet', '2024-03-08'::date, true, 67),
  ('svjl', 'svjl', 'SVJL: Terastal Charizard ex Battle Master Deck', 'Japanese Scarlet & Violet', '2024-05-17'::date, true, 21),
  ('svjp', 'svjp', 'SVJP: Chien-Pao ex Battle Master Deck', 'Japanese Scarlet & Violet', '2024-05-17'::date, true, 19),
  ('svk', 'svk', 'SVK: Stellar Miracle Deck Build Box', 'Japanese Scarlet & Violet', '2024-07-19'::date, true, 44),
  ('svln', 'svln', 'SVLN: Sylveon ex Stellar Tera Type Starter Set', 'Japanese Scarlet & Violet', '2024-08-30'::date, true, 22),
  ('svls', 'svls', 'SVLS: Ceruledge ex Stellar Tera Type Starter Set', 'Japanese Scarlet & Violet', '2024-08-30'::date, true, 22),
  ('svm', 'svm', 'SVM: Generations Start Decks', 'Japanese Scarlet & Violet', '2024-11-22'::date, true, 175),
  ('svn', 'svn', 'SVN: Battle Partners Deck Build Box', 'Japanese Scarlet & Violet', '2025-01-24'::date, true, 45),
  ('svod', 'svod', 'SVOD: ex Starter Set Steven''s Beldum & Metagross ex', 'Japanese Scarlet & Violet', '2025-02-21'::date, true, 19),
  ('svom', 'svom', 'SVOM: ex Starter Set Marnie''s Morpeko & Grimmsnarl ex', 'Japanese Scarlet & Violet', '2025-02-21'::date, true, 20),
  ('svp1', 'svp1', 'SVP1: ex Special Set', 'Japanese Scarlet & Violet', '2023-05-19'::date, true, 7),
  ('szd', 'szd', 'SZD: Hydreigon Half Deck', 'Japanese Black & White', '2012-03-16'::date, true, 16),
  ('wak', 'wak', 'WAK: Everyone''s Exciting Battle', 'Japanese Black & White', '2012-11-16'::date, true, 48),
  ('wcp', 'wcp', 'WCP: World Champions Pack', 'Japanese Diamond & Pearl', '2007-07-05'::date, true, 108),
  ('wcs23', 'wcs23', 'WCS23: 2023 World Championships Yokohama Deck: Pikachu', 'Japanese Scarlet & Violet', '2023-07-28'::date, true, 31),
  ('x30', 'x30', 'X30: Xerneas Half Deck', 'Japanese XY', '2014-01-31'::date, true, 15),
  ('xy', 'xy', 'XY: The Best of XY', 'Japanese Sun & Moon', '2017-04-21'::date, true, 186),
  ('xy1-bx', 'xy1-bx', 'XY1-Bx: Collection X', 'Japanese XY', '2013-12-13'::date, true, 63),
  ('xy1-by', 'xy1-by', 'XY1-By: Collection Y', 'Japanese XY', '2013-12-13'::date, true, 63),
  ('xy10-b', 'xy10-b', 'XY10-B: Awakening Psychic King', 'Japanese XY', '2016-03-18'::date, true, 87),
  ('xy11-bb', 'xy11-bb', 'XY11-Bb: Fever-Burst Fighter', 'Japanese XY', '2016-06-17'::date, true, 58),
  ('xy11-br', 'xy11-br', 'XY11-Br: Cruel Traitor', 'Japanese XY', '2016-06-17'::date, true, 58),
  ('xy2', 'ja-xy2', 'XY2: Wild Blaze', 'Japanese XY', '2014-03-15'::date, true, 87),
  ('xy3', 'ja-xy3', 'XY3: Rising Fist', 'Japanese XY', '2014-06-14'::date, true, 103),
  ('xy4', 'ja-xy4', 'XY4: Phantom Gate', 'Japanese XY', '2014-09-13'::date, true, 95),
  ('xy5-bg', 'xy5-bg', 'XY5-Bg: Gaia Volcano', 'Japanese XY', '2014-12-13'::date, true, 78),
  ('xy5-bt', 'xy5-bt', 'XY5-Bt: Tidal Storm', 'Japanese XY', '2014-12-13'::date, true, 78),
  ('xy6', 'xy6-b', 'XY6: Emerald Break', 'Japanese XY', '2015-03-14'::date, false, 11),
  ('xy6-b', 'xy6-b', 'XY6-B: Emerald Break', 'Japanese XY', '2015-03-14'::date, true, 78),
  ('xy7', 'xy7-b', 'XY7: Bandit Ring', 'Japanese XY', '2015-06-20'::date, false, 11),
  ('xy7-b', 'xy7-b', 'XY7-B: Bandit Ring', 'Japanese XY', '2015-06-20'::date, true, 84),
  ('xy8-bb', 'xy8-bb', 'XY8-Bb: Blue Shock', 'Japanese XY', '2015-09-26'::date, true, 64),
  ('xy8-br', 'xy8-br', 'XY8-Br: Red Flash', 'Japanese XY', '2015-09-26'::date, true, 64),
  ('xy9-b', 'xy9-b', 'XY9-B: Rage of the Broken Heavens', 'Japanese XY', '2015-12-11'::date, true, 88),
  ('xya', 'xya', 'XYA: M Charizard-EX Mega Battle Deck', 'Japanese XY', '2014-03-15'::date, true, 22),
  ('xyb', 'xyb', 'XYB: Dialga-EX + Aegislash-EX Hyper Metal Chain Deck', 'Japanese XY', '2014-09-13'::date, true, 19),
  ('xyc', 'xyc', 'XYC: Super Legend Set: Xerneas-EX & Yveltal-EX', 'Japanese XY', '2014-11-14'::date, true, 24),
  ('xyd', 'xyd', 'XYD: M Rayquaza-EX Mega Battle Deck', 'Japanese XY', '2015-03-14'::date, true, 19),
  ('xye', 'xye', 'XYE: Emboar-EX vs Togekiss-EX Deck Kit', 'Japanese XY', '2015-07-18'::date, true, 23),
  ('xyf', 'xyf', 'XYF: Golduck BREAK + Palkia-EX Combo Deck', 'Japanese XY', '2015-10-09'::date, true, 17),
  ('xyg', 'xyg', 'XYG: Zygarde-EX Perfect Battle Deck', 'Japanese XY', '2016-03-18'::date, true, 20),
  ('xyh', 'xyh', 'XYH: M Audino-EX Mega Battle Deck', 'Japanese XY', '2016-03-18'::date, true, 27),
  ('xyp', 'ja-xyp', 'XYP: XY Promos', 'Japanese XY', '2013-08-01'::date, true, 300),
  ('y30', 'y30', 'Y30: Yveltal Half Deck', 'Japanese XY', '2014-01-31'::date, true, 15);

-- Preconditions
DO $$
DECLARE n integer;
BEGIN
  SELECT count(*) INTO n FROM ptcgdb_set_names;
  IF n <> 314 THEN RAISE EXCEPTION 'name table has % codes, expected 314', n; END IF;

  SELECT count(*) INTO n FROM public.cards c
   WHERE c.origin = 'ptcgdb'
     AND NOT EXISTS (SELECT 1 FROM ptcgdb_set_names j WHERE c.set_id IN (j.code, j.set_id));
  IF n <> 0 THEN RAISE EXCEPTION '% ptcgdb cards are on a set the name table does not know', n; END IF;

  SELECT count(*) INTO n FROM public.sets s JOIN ptcgdb_set_names j ON j.owns_set AND s.id = j.set_id
   WHERE s.origin <> 'ptcgdb';
  IF n <> 0 THEN RAISE EXCEPTION '% published ptcgdb set IDs belong to another origin', n; END IF;
END $$;

-- 1. Name the ptcgdb sets; insert the ja-* sets.
INSERT INTO public.sets (id, name, series, release_date, origin)
SELECT set_id, name, series, release_date, 'ptcgdb'
  FROM ptcgdb_set_names
 WHERE owns_set
ON CONFLICT (id) DO UPDATE
   SET name = EXCLUDED.name,
       series = EXCLUDED.series,
       release_date = EXCLUDED.release_date
 WHERE public.sets.origin = 'ptcgdb';

-- 2. Move cards whose code is published under another set ID (card IDs unchanged).
UPDATE public.cards c
   SET set_id = j.set_id
  FROM ptcgdb_set_names j
 WHERE c.origin = 'ptcgdb'
   AND c.set_id = j.code
   AND j.set_id <> j.code;

-- 3. Card set name and series from the published set.
UPDATE public.cards c
   SET set_name = s.name,
       set_series = s.series
  FROM public.sets s
 WHERE c.origin = 'ptcgdb'
   AND s.id = c.set_id
   AND s.origin = 'ptcgdb'
   AND (c.set_name, c.set_series) IS DISTINCT FROM (s.name, s.series);

-- 4. Checks (any failure rolls everything back).
DO $$
DECLARE n integer;
BEGIN
  SELECT count(*) INTO n FROM public.cards WHERE origin = 'ptcgdb';
  IF n <> 19705 THEN RAISE EXCEPTION 'ptcgdb card count is %, expected 19705', n; END IF;

  SELECT count(*) INTO n FROM public.cards WHERE origin = 'ptcgdb' AND (set_name IS NULL OR set_series IS NULL);
  IF n <> 0 THEN RAISE EXCEPTION '% ptcgdb cards still have no set name or series', n; END IF;

  SELECT count(*) INTO n FROM public.cards c LEFT JOIN public.sets s ON s.id = c.set_id
   WHERE c.origin = 'ptcgdb' AND s.origin IS DISTINCT FROM 'ptcgdb';
  IF n <> 0 THEN RAISE EXCEPTION '% ptcgdb cards are on a set another origin owns', n; END IF;

  SELECT count(*) INTO n FROM public.cards c
   WHERE c.origin = 'ptcgdb'
     AND NOT EXISTS (SELECT 1 FROM ptcgdb_set_names j
                      WHERE j.set_id = c.set_id AND j.code = lower(c.raw_data->>'set_name'));
  IF n <> 0 THEN RAISE EXCEPTION '% ptcgdb cards are not on the set their code maps to', n; END IF;

  SELECT count(*) INTO n FROM (
    SELECT j.set_id, sum(j.cards) AS expected FROM ptcgdb_set_names j GROUP BY j.set_id
  ) e
  LEFT JOIN (
    SELECT set_id, count(*) AS actual FROM public.cards WHERE origin = 'ptcgdb' GROUP BY set_id
  ) a ON a.set_id = e.set_id
  WHERE a.actual IS DISTINCT FROM e.expected;
  IF n <> 0 THEN RAISE EXCEPTION '% ptcgdb sets have a card count other than the name table''s', n; END IF;

  SELECT count(*) INTO n FROM public.sets s JOIN ptcgdb_set_names j ON j.owns_set AND s.id = j.set_id
   WHERE s.origin = 'ptcgdb' AND s.name = j.name AND s.series = j.series
     AND s.release_date IS NOT DISTINCT FROM j.release_date;
  IF n <> 312 THEN RAISE EXCEPTION 'only % of 312 ptcgdb sets carry the reviewed name', n; END IF;
END $$;

SELECT public.refresh_explore_filter_options();

COMMIT;
